/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "selector",
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        'surface': 'hsl(var(--surface))',
        'surface-dim': 'hsl(var(--surface-dim))',
        'surface-bright': 'hsl(var(--surface-bright))',
        'surface-container-lowest': 'hsl(var(--surface-container-lowest))',
        'surface-container-low': 'hsl(var(--surface-container-low))',
        'surface-container': 'hsl(var(--surface-container))',
        'surface-container-high': 'hsl(var(--surface-container-high))',
        'surface-container-highest': 'hsl(var(--surface-container-highest))',
        'on-surface': 'hsl(var(--on-surface))',
        'on-surface-variant': 'hsl(var(--on-surface-variant))',
        'inverse-surface': 'hsl(var(--inverse-surface))',
        'inverse-on-surface': 'hsl(var(--inverse-on-surface))',
        'outline': 'hsl(var(--outline))',
        'outline-variant': 'hsl(var(--outline-variant))',
        'surface-tint': 'hsl(var(--surface-tint))',
        'on-primary': 'hsl(var(--on-primary))',
        'primary-container': 'hsl(var(--primary-container))',
        'on-primary-container': 'hsl(var(--on-primary-container))',
        'inverse-primary': 'hsl(var(--inverse-primary))',
        'on-secondary': 'hsl(var(--on-secondary))',
        'secondary-container': 'hsl(var(--secondary-container))',
        'on-secondary-container': 'hsl(var(--on-secondary-container))',
        'tertiary': 'hsl(var(--tertiary))',
        'on-tertiary': 'hsl(var(--on-tertiary))',
        'tertiary-container': 'hsl(var(--tertiary-container))',
        'on-tertiary-container': 'hsl(var(--on-tertiary-container))',
        'error': 'hsl(var(--error))',
        'on-error': 'hsl(var(--on-error))',
        'error-container': 'hsl(var(--error-container))',
        'on-error-container': 'hsl(var(--on-error-container))',
        'primary-fixed': 'hsl(var(--primary-fixed))',
        'primary-fixed-dim': 'hsl(var(--primary-fixed-dim))',
        'on-primary-fixed': 'hsl(var(--on-primary-fixed))',
        'on-primary-fixed-variant': 'hsl(var(--on-primary-fixed-variant))',
        'secondary-fixed': 'hsl(var(--secondary-fixed))',
        'secondary-fixed-dim': 'hsl(var(--secondary-fixed-dim))',
        'on-secondary-fixed': 'hsl(var(--on-secondary-fixed))',
        'on-secondary-fixed-variant': 'hsl(var(--on-secondary-fixed-variant))',
        'tertiary-fixed': 'hsl(var(--tertiary-fixed))',
        'tertiary-fixed-dim': 'hsl(var(--tertiary-fixed-dim))',
        'on-tertiary-fixed': 'hsl(var(--on-tertiary-fixed))',
        'on-tertiary-fixed-variant': 'hsl(var(--on-tertiary-fixed-variant))',
        'on-background': 'hsl(var(--on-background))',
        'surface-variant': 'hsl(var(--surface-variant))',
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        'margin-page': "64px",
        'container-max': "1200px",
        'sidebar-width': "280px",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
        'display-lg': ["var(--font-geist-sans)", "sans-serif"],
        'headline-md': ["var(--font-geist-sans)", "sans-serif"],
        'headline-md-mobile': ["var(--font-geist-sans)", "sans-serif"],
        'title-sm': ["var(--font-geist-sans)", "sans-serif"],
        'body-md': ["var(--font-geist-sans)", "sans-serif"],
        'label-caps': ["var(--font-geist-sans)", "sans-serif"],
        'code': ["var(--font-geist-mono)", "monospace"],
      },
      fontSize: {
        'display-lg': ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        'headline-md': ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
        'headline-md-mobile': ["24px", { lineHeight: "32px", fontWeight: "500" }],
        'title-sm': ["18px", { lineHeight: "24px", fontWeight: "600" }],
        'body-md': ["15px", { lineHeight: "24px", fontWeight: "400" }],
        'label-caps': ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        'code': ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}