import Link from "next/link";
import { auth } from "auth";
import { redirect } from "next/navigation";
import Header from "@/components/header";
import { Sparkles, BookOpen, Network, Share2, Compass } from "lucide-react";

export default async function LandingPage() {
  // 1. Redirect to profile page if user is already authenticated
  const session = await auth();
  if (session?.user?.username) {
    redirect(`/u/${session.user.username}`);
  }

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-b from-[#FAF9F6] via-white to-[#F4F3EF] text-slate-800">
      {/* Navigation Header */}
      <Header />

      {/* Main Content */}
      <main className="flex-1 flex flex-col items-center justify-center py-20 px-4 max-w-5xl mx-auto w-full gap-20">
        {/* Hero Section */}
        <section className="flex flex-col items-center text-center space-y-8 max-w-3xl">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-indigo-50 border border-indigo-100 text-indigo-700 text-xs font-semibold tracking-wide animate-pulse">
            <Sparkles className="h-3.5 w-3.5" />
            Next-Generation Documentation
          </div>

          <h1 className="text-5xl font-extrabold sm:text-6xl tracking-tight text-slate-900 leading-tight">
            Turn documents into <br />
            <span className="bg-gradient-to-r from-indigo-600 via-purple-600 to-indigo-700 bg-clip-text text-transparent">
              structured knowledge webs
            </span>
          </h1>

          <p className="text-lg text-slate-600 leading-relaxed max-w-2xl font-serif">
            A minimalist, academic-style documentation platform inspired by Wikipedia and GitBook. 
            Upload papers, reports, or articles, and instantly visualize their interconnected concepts.
          </p>

          {/* Call-to-actions */}
          <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
            <Link href="/signup">
              <button className="bg-indigo-600 text-white hover:bg-indigo-700 shadow-md hover:shadow-lg transition-all font-semibold px-8 py-3 rounded-lg text-sm flex items-center gap-2 transform hover:-translate-y-0.5">
                Get Started Free <Sparkles className="h-4 w-4" />
              </button>
            </Link>
            <Link href="/signin">
              <button className="bg-white text-slate-700 hover:text-slate-900 border border-slate-200 hover:border-slate-300 shadow-sm hover:shadow-md transition-all font-semibold px-8 py-3 rounded-lg text-sm">
                Sign In
              </button>
            </Link>
          </div>
        </section>

        {/* Visual Showcase: Monospace SVG Knowledge Graph */}
        <section className="w-full max-w-xl bg-white/70 backdrop-blur-md rounded-2xl border border-slate-200/80 p-8 shadow-xl relative overflow-hidden group hover:border-slate-300/80 transition-all duration-300">
          <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-100 rounded-full blur-3xl -z-10 opacity-60 group-hover:opacity-100 transition-opacity" />
          <div className="absolute bottom-0 left-0 w-32 h-32 bg-teal-100 rounded-full blur-3xl -z-10 opacity-60 group-hover:opacity-100 transition-opacity" />

          <div className="text-center space-y-2 mb-8">
            <span className="text-[10px] font-bold uppercase tracking-widest text-indigo-600 font-mono">
              Knowledge Map Visualization
            </span>
            <p className="text-xs text-slate-500 font-medium">
              Autogenerated connections between ingested topics.
            </p>
          </div>
          
          <div className="relative flex justify-center items-center h-[200px] w-full">
            <svg width="340" height="200" viewBox="0 0 340 200" className="mx-auto text-slate-800 font-mono select-none">
              {/* Connection Lines */}
              <path d="M 170 35 L 75 90" stroke="#818CF8" strokeWidth="1.5" strokeDasharray="3,3" />
              <path d="M 170 35 L 265 90" stroke="#818CF8" strokeWidth="1.5" strokeDasharray="3,3" />
              <path d="M 75 90 L 170 145" stroke="#14B8A6" strokeWidth="1.5" />
              <path d="M 265 90 L 170 145" stroke="#14B8A6" strokeWidth="1.5" />
              <path d="M 170 35 L 170 145" stroke="#6366F1" strokeWidth="2" />

              {/* Node 1: Root - Statistics */}
              <g className="cursor-pointer group/node">
                <circle cx="170" cy="35" r="22" className="fill-white stroke-indigo-600 transition-colors" strokeWidth="2" />
                <circle cx="170" cy="35" r="4" className="fill-indigo-600 animate-ping" />
                <circle cx="170" cy="35" r="4" className="fill-indigo-600" />
                <text x="170" y="70" textAnchor="middle" fill="#0F172A" fontSize="10" fontWeight="bold">Statistics</text>
              </g>

              {/* Node 2: Left - Data Science */}
              <g className="cursor-pointer group/node">
                <circle cx="75" cy="90" r="20" className="fill-white stroke-teal-500 transition-colors" strokeWidth="2" />
                <circle cx="75" cy="90" r="3" className="fill-teal-500" />
                <text x="75" y="125" textAnchor="middle" fill="#0F172A" fontSize="10" fontWeight="bold">Data Science</text>
              </g>

              {/* Node 3: Right - AI Parallels */}
              <g className="cursor-pointer group/node">
                <circle cx="265" cy="90" r="20" className="fill-white stroke-indigo-400 transition-colors" strokeWidth="2" />
                <circle cx="265" cy="90" r="3" className="fill-indigo-400" />
                <text x="265" y="125" textAnchor="middle" fill="#0F172A" fontSize="10" fontWeight="bold">Artificial Intelligence</text>
              </g>

              {/* Node 4: Bottom - Machine Learning */}
              <g className="cursor-pointer group/node">
                <circle cx="170" cy="145" r="24" className="fill-white stroke-indigo-700 transition-colors" strokeWidth="2.5" />
                <circle cx="170" cy="145" r="5" className="fill-indigo-700" />
                <text x="170" y="182" textAnchor="middle" fill="#0F172A" fontSize="10" fontWeight="bold">Machine Learning</text>
              </g>
            </svg>
          </div>
        </section>

        {/* Feature Grid */}
        <section className="w-full grid md:grid-cols-3 gap-6 pt-6">
          <div className="p-6 bg-white border border-slate-200 rounded-xl hover:border-indigo-200 transition-all flex flex-col gap-3 shadow-xs">
            <div className="w-10 h-10 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center">
              <Network className="h-5 w-5" />
            </div>
            <h3 className="font-bold text-slate-900 text-sm">Interactive Graph View</h3>
            <p className="text-xs text-slate-500 leading-relaxed font-serif">
              Explore complex relationships between subjects dynamically using an interactive force-directed visual map.
            </p>
          </div>

          <div className="p-6 bg-white border border-slate-200 rounded-xl hover:border-indigo-200 transition-all flex flex-col gap-3 shadow-xs">
            <div className="w-10 h-10 rounded-lg bg-teal-50 text-teal-605 flex items-center justify-center">
              <BookOpen className="h-5 w-5" />
            </div>
            <h3 className="font-bold text-slate-900 text-sm">Academic Structure</h3>
            <p className="text-xs text-slate-500 leading-relaxed font-serif">
              Clean citation footnotes, semantic linking, and source mapping optimized for documentation reading.
            </p>
          </div>

          <div className="p-6 bg-white border border-slate-200 rounded-xl hover:border-indigo-200 transition-all flex flex-col gap-3 shadow-xs">
            <div className="w-10 h-10 rounded-lg bg-purple-50 text-purple-600 flex items-center justify-center">
              <Share2 className="h-5 w-5" />
            </div>
            <h3 className="font-bold text-slate-900 text-sm">Fast Sharing</h3>
            <p className="text-xs text-slate-500 leading-relaxed font-serif">
              Publish public wikis, share unlisted research, or keep folders private as your personal second brain.
            </p>
          </div>
        </section>

        {/* Recently Published Wikis Section */}
        <section className="w-full space-y-6 border-t border-slate-200 pt-16 text-center">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest font-mono flex items-center justify-center gap-1.5">
            <Compass className="h-4 w-4 text-slate-400" />
            Explore Recently Published Wikis
          </h3>
          
          <div className="grid gap-6 sm:grid-cols-3">
            <div className="group rounded-xl border border-slate-200 bg-white p-5 text-left hover:border-indigo-300 hover:shadow-md transition-all">
              <span className="text-indigo-650 font-bold text-sm group-hover:underline block truncate">
                Machine Learning Atlas
              </span>
              <p className="text-xs text-slate-500 mt-2 font-serif line-clamp-2 leading-relaxed">
                A comprehensive knowledge directory mapping concepts and references.
              </p>
              <div className="flex items-center justify-between mt-4 pt-3 border-t border-slate-100 text-[10px] text-slate-400 font-mono">
                <span>8 pages</span>
                <span className="bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-100 uppercase">Public</span>
              </div>
            </div>

            <div className="group rounded-xl border border-slate-200 bg-white p-5 text-left hover:border-indigo-300 hover:shadow-md transition-all">
              <span className="text-indigo-650 font-bold text-sm group-hover:underline block truncate">
                Startup Handbook
              </span>
              <p className="text-xs text-slate-500 mt-2 font-serif line-clamp-2 leading-relaxed">
                Aggregating foundational paradigms and operational guidelines.
              </p>
              <div className="flex items-center justify-between mt-4 pt-3 border-t border-slate-100 text-[10px] text-slate-400 font-mono">
                <span>12 pages</span>
                <span className="bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-100 uppercase">Public</span>
              </div>
            </div>

            <div className="group rounded-xl border border-slate-200 bg-white p-5 text-left hover:border-indigo-300 hover:shadow-md transition-all">
              <span className="text-indigo-650 font-bold text-sm group-hover:underline block truncate">
                Travel Knowledge Base
              </span>
              <p className="text-xs text-slate-500 mt-2 font-serif line-clamp-2 leading-relaxed">
                Structured reference documentation organizing travel logistics.
              </p>
              <div className="flex items-center justify-between mt-4 pt-3 border-t border-slate-100 text-[10px] text-slate-400 font-mono">
                <span>5 pages</span>
                <span className="bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-100 uppercase">Public</span>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 py-6 text-center text-xs text-slate-400 font-mono">
        &copy; {new Date().getFullYear()} Instant Wiki. Built for documentation precision.
      </footer>
    </div>
  );
}