"""
InstantWiki MarkItDown Microservice
====================================
A self-contained FastAPI server that exposes document-to-markdown conversion
via HTTP. TypeScript callers use the HTTP API instead of spawning Python processes.

Start with:
    python server.py
    # or
    uvicorn server:app --host 127.0.0.1 --port 5100
"""

import os
import sys
import json
import tempfile
import base64
import re
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import uvicorn

# Load .env from the web app directory (two levels up: services/markitdown -> web)
_service_dir = Path(__file__).resolve().parent
_web_dir = _service_dir.parent.parent  # apps/web
_dotenv_path = _web_dir / ".env"

try:
    from dotenv import load_dotenv
    load_dotenv(_dotenv_path)
except ImportError:
    pass

# --- MarkItDown + PyMuPDF imports ---
import fitz  # PyMuPDF
from markitdown import MarkItDown

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------
app = FastAPI(
    title="InstantWiki MarkItDown Service",
    version="1.0.0",
    description="Document-to-Markdown conversion microservice",
)


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------
class ConvertRequest(BaseModel):
    file_path: str
    page_limit: Optional[int] = None


class GenerateTestDocxRequest(BaseModel):
    output_path: str


class ConvertBatchRequest(BaseModel):
    file_paths: list[str]
    page_limit: Optional[int] = None


class ConvertFromBytesRequest(BaseModel):
    file_bytes_base64: str
    filename: str  # needed to infer file type from extension
    page_limit: Optional[int] = None


class BlockData(BaseModel):
    type: str
    content: str
    level: Optional[int] = None


class PageData(BaseModel):
    page_number: int
    text: str
    blocks: list[BlockData] = []


class ConvertResponse(BaseModel):
    success: bool
    pages: list[PageData] = []
    images: list = []
    error: Optional[str] = None


# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------
@app.get("/health")
async def health():
    return {"status": "ok", "service": "markitdown"}


# ---------------------------------------------------------------------------
# Test-helper: generate a minimal DOCX for integration testing
# ---------------------------------------------------------------------------
@app.post("/generate-test-docx")
async def generate_test_docx(req: GenerateTestDocxRequest):
    """Write a minimal .docx to the given path using python-docx."""
    try:
        from docx import Document as DocxDocument  # python-docx

        doc = DocxDocument()
        doc.add_heading("Test DOCX Document", level=1)
        doc.add_paragraph(
            "This is a test document generated by the MarkItDown microservice "
            "to verify DOCX conversion works end-to-end."
        )
        doc.add_heading("Section 2 – Tables", level=2)
        table = doc.add_table(rows=2, cols=3)
        table.rows[0].cells[0].text = "Column A"
        table.rows[0].cells[1].text = "Column B"
        table.rows[0].cells[2].text = "Column C"
        table.rows[1].cells[0].text = "Value 1"
        table.rows[1].cells[1].text = "Value 2"
        table.rows[1].cells[2].text = "Value 3"
        doc.add_paragraph("End of test document.")
        doc.save(req.output_path)
        return {"success": True, "path": req.output_path}
    except ImportError:
        raise HTTPException(status_code=500, detail="python-docx not installed in this venv")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ---------------------------------------------------------------------------
# Conversion endpoint
# ---------------------------------------------------------------------------
@app.post("/convert", response_model=ConvertResponse)
async def convert_document(req: ConvertRequest):
    """Convert a single document file by path."""
    file_path = req.file_path
    page_limit = req.page_limit

    if not os.path.isfile(file_path):
        raise HTTPException(status_code=400, detail=f"File not found: {file_path}")

    try:
        markitdown_instance = _get_markitdown_instance()
        ext = os.path.splitext(file_path)[1].lower()

        if ext == ".pdf":
            pages_data = _extract_pdf_pages(file_path, markitdown_instance, page_limit)
        else:
            res = markitdown_instance.convert(file_path)
            md_text = res.text_content
            blocks_data = _parse_markdown_to_blocks(md_text)
            if not blocks_data:
                blocks_data = [{"type": "text", "content": md_text}]
            pages_data = [{"page_number": 1, "text": md_text, "blocks": blocks_data}]

        return ConvertResponse(success=True, pages=pages_data, images=[])

    except Exception as e:
        return ConvertResponse(success=False, error=str(e))


# ---------------------------------------------------------------------------
# Batch conversion: convert multiple files in one request
# ---------------------------------------------------------------------------
@app.post("/convert-batch")
async def convert_batch(req: ConvertBatchRequest):
    """Convert multiple documents in batch. Returns a list of results."""
    results = []
    
    for file_path in req.file_paths:
        if not os.path.isfile(file_path):
            results.append({
                "file_path": file_path,
                "success": False,
                "error": f"File not found: {file_path}",
                "pages": [],
                "images": []
            })
            continue
        
        try:
            markitdown_instance = _get_markitdown_instance()
            ext = os.path.splitext(file_path)[1].lower()

            if ext == ".pdf":
                pages_data = _extract_pdf_pages(file_path, markitdown_instance, req.page_limit)
            else:
                res = markitdown_instance.convert(file_path)
                md_text = res.text_content
                blocks_data = _parse_markdown_to_blocks(md_text)
                if not blocks_data:
                    blocks_data = [{"type": "text", "content": md_text}]
                pages_data = [{"page_number": 1, "text": md_text, "blocks": blocks_data}]

            results.append({
                "file_path": file_path,
                "success": True,
                "pages": pages_data,
                "images": []
            })

        except Exception as e:
            results.append({
                "file_path": file_path,
                "success": False,
                "error": str(e),
                "pages": [],
                "images": []
            })
    
    return {"results": results}


# ---------------------------------------------------------------------------
# Convert from base64-encoded bytes (no filesystem access needed)
# ---------------------------------------------------------------------------
@app.post("/convert-bytes", response_model=ConvertResponse)
async def convert_from_bytes(req: ConvertFromBytesRequest):
    """
    Convert a document from base64-encoded bytes.
    Useful when the file is in memory or coming from an upload stream.
    """
    try:
        file_bytes = base64.b64decode(req.file_bytes_base64)
        ext = os.path.splitext(req.filename)[1].lower()
        
        # Write to temp file, convert, then delete
        fd, temp_path = tempfile.mkstemp(suffix=ext)
        os.close(fd)
        
        try:
            with open(temp_path, "wb") as f:
                f.write(file_bytes)
            
            markitdown_instance = _get_markitdown_instance()
            
            if ext == ".pdf":
                pages_data = _extract_pdf_pages(temp_path, markitdown_instance, req.page_limit)
            else:
                res = markitdown_instance.convert(temp_path)
                md_text = res.text_content
                blocks_data = _parse_markdown_to_blocks(md_text)
                if not blocks_data:
                    blocks_data = [{"type": "text", "content": md_text}]
                pages_data = [{"page_number": 1, "text": md_text, "blocks": blocks_data}]
            
            return ConvertResponse(success=True, pages=pages_data, images=[])
        
        finally:
            if os.path.exists(temp_path):
                os.unlink(temp_path)
    
    except Exception as e:
        return ConvertResponse(success=False, error=str(e))


# ---------------------------------------------------------------------------
# List supported file formats
# ---------------------------------------------------------------------------
@app.get("/formats")
async def list_supported_formats():
    """Return a list of supported document formats."""
    return {
        "formats": [
            {"extension": ".pdf", "mime_type": "application/pdf", "description": "PDF documents"},
            {"extension": ".docx", "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "description": "Microsoft Word (DOCX)"},
            {"extension": ".doc", "mime_type": "application/msword", "description": "Microsoft Word (DOC)"},
            {"extension": ".pptx", "mime_type": "application/vnd.openxmlformats-officedocument.presentationml.presentation", "description": "Microsoft PowerPoint (PPTX)"},
            {"extension": ".xlsx", "mime_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "description": "Microsoft Excel (XLSX)"},
            {"extension": ".xls", "mime_type": "application/vnd.ms-excel", "description": "Microsoft Excel (XLS)"},
            {"extension": ".html", "mime_type": "text/html", "description": "HTML documents"},
            {"extension": ".xml", "mime_type": "text/xml", "description": "XML documents"},
            {"extension": ".csv", "mime_type": "text/csv", "description": "CSV files"},
            {"extension": ".md", "mime_type": "text/markdown", "description": "Markdown files"},
            {"extension": ".txt", "mime_type": "text/plain", "description": "Plain text files"},
            {"extension": ".epub", "mime_type": "application/epub+zip", "description": "EPUB ebooks"},
            {"extension": ".zip", "mime_type": "application/zip", "description": "ZIP archives (extracts and converts contents)"},
        ],
        "with_ocr": ["pdf", "docx", "pptx", "xlsx"],
        "requires_llm": "Optional: LLM client enables OCR for images in documents"
    }


# ---------------------------------------------------------------------------
# Get service info and status
# ---------------------------------------------------------------------------
@app.get("/info")
async def service_info():
    """Return service version, configuration, and status."""
    openai_configured = bool(
        os.environ.get("OPENAI_API_KEY") and 
        os.environ.get("OPENAI_API_KEY") != "YOUR_OPENAI_API_KEY"
    )
    
    return {
        "service": "InstantWiki MarkItDown Microservice",
        "version": "1.0.0",
        "markitdown_version": "0.1.6",  # Update if needed
        "llm_configured": openai_configured,
        "ocr_available": openai_configured,
        "endpoints": {
            "health": "GET /health",
            "convert": "POST /convert",
            "convert_batch": "POST /convert-batch",
            "convert_bytes": "POST /convert-bytes",
            "formats": "GET /formats",
            "info": "GET /info",
            "generate_test_docx": "POST /generate-test-docx"
        }
    }


# ---------------------------------------------------------------------------
# MarkItDown instance factory
# ---------------------------------------------------------------------------
def _get_markitdown_instance() -> MarkItDown:
    """Create a MarkItDown instance, optionally with LLM client."""
    openai_key = os.environ.get("OPENAI_API_KEY")
    openai_base = os.environ.get("OPENAI_BASE_URL")
    llm_model = "openai.gpt-oss-120b"
    client = None

    if openai_key and openai_key.strip() and openai_key != "YOUR_OPENAI_API_KEY":
        try:
            from openai import OpenAI

            test_client = OpenAI(
                api_key=openai_key,
                base_url=openai_base if openai_base else None,
                timeout=3.0,
            )
            test_client.chat.completions.create(
                model=llm_model,
                messages=[{"role": "user", "content": "ping"}],
                max_tokens=1,
            )
            client = test_client
        except Exception:
            client = None

    if client:
        return MarkItDown(llm_client=client, llm_model=llm_model, enable_plugins=True)
    else:
        return MarkItDown(enable_plugins=True)


# ---------------------------------------------------------------------------
# PDF page-by-page extraction
# ---------------------------------------------------------------------------
def _extract_pdf_pages(
    pdf_path: str, markitdown: MarkItDown, page_limit: Optional[int] = None
) -> list[dict]:
    doc = fitz.open(pdf_path)
    total_pages = len(doc)
    pages_to_process = (
        range(min(page_limit, total_pages))
        if page_limit is not None
        else range(total_pages)
    )

    pages_data = []
    for page_idx in pages_to_process:
        page_num = page_idx + 1
        page = doc[page_idx]

        # Extract single page as temporary PDF
        page_doc = fitz.open()
        page_doc.insert_pdf(doc, from_page=page_idx, to_page=page_idx)

        fd, temp_pdf_path = tempfile.mkstemp(suffix=".pdf")
        os.close(fd)

        try:
            page_doc.save(temp_pdf_path)
            page_doc.close()

            res = markitdown.convert(temp_pdf_path)
            page_text = res.text_content

            # Strip generic "## Page 1" injected by markitdown for single-page exports
            page_text = re.sub(
                r"^#+\s*Page\s+1\s*\n?", "", page_text, flags=re.IGNORECASE
            ).strip()

            # Extract PyMuPDF text for comparison
            fitz_text = page.get_text("text").strip()

            # Decide which text source to use
            use_fitz = False
            if len(page_text) < 50 and len(fitz_text) >= 50:
                use_fitz = True
            elif len(page_text) > 0:
                mid_alnum_space = sum(
                    1 for c in page_text if c.isalnum() or c.isspace()
                )
                fitz_alnum_space = sum(
                    1 for c in fitz_text if c.isalnum() or c.isspace()
                )
                mid_ratio = (
                    mid_alnum_space / len(page_text) if len(page_text) > 0 else 0
                )
                fitz_ratio = (
                    fitz_alnum_space / len(fitz_text) if len(fitz_text) > 0 else 0
                )

                if mid_ratio < 0.6 and fitz_ratio > 0.8 and len(fitz_text) > 100:
                    use_fitz = True
                elif len(fitz_text) > len(page_text) * 1.5:
                    use_fitz = True

            if use_fitz:
                lines = fitz_text.splitlines()
                cleaned_lines = []
                i = 0
                while i < len(lines):
                    line = lines[i].strip()
                    if line in ["•", "–", "▪", "*", "-"] or (
                        len(line) == 1 and not line.isalnum()
                    ):
                        if i + 1 < len(lines):
                            next_line = lines[i + 1].strip()
                            cleaned_lines.append(f"{line} {next_line}")
                            i += 2
                            continue
                    cleaned_lines.append(lines[i])
                    i += 1
                page_text = "\n".join(cleaned_lines)

            # Inject topic heading if none exists
            existing_heading = re.match(r"^#+\s+.+", page_text.lstrip())
            if not existing_heading:
                topic = _extract_content_topic(page_text)
                if topic:
                    page_text = f"## {topic}\n\n{page_text}"

            # Extract images from this page
            image_list = page.get_images(full=True)
            seen_xrefs = set()
            img_index = 1
            for img in image_list:
                try:
                    xref = img[0]
                    if xref in seen_xrefs:
                        continue
                    seen_xrefs.add(xref)

                    width = img[2]
                    height = img[3]
                    if width < 50 or height < 50:
                        continue

                    base_image = doc.extract_image(xref)
                    image_bytes = base_image["image"]
                    image_ext = base_image["ext"]

                    base64_data = base64.b64encode(image_bytes).decode("utf-8")
                    mime_type = f"image/{image_ext}"
                    if image_ext == "jpg":
                        mime_type = "image/jpeg"

                    page_text += f"\n\n![Image page {page_num}, image {img_index}](data:{mime_type};base64,{base64_data})"
                    img_index += 1
                except Exception:
                    pass

            blocks_data = _parse_markdown_to_blocks(page_text)
            if not blocks_data:
                blocks_data = [{"type": "text", "content": page_text}]

            pages_data.append(
                {"page_number": page_num, "text": page_text, "blocks": blocks_data}
            )
        finally:
            if os.path.exists(temp_pdf_path):
                os.unlink(temp_pdf_path)

    doc.close()
    return pages_data


# ---------------------------------------------------------------------------
# Markdown parsing helpers
# ---------------------------------------------------------------------------
def _parse_markdown_to_blocks(md_text: str) -> list[dict]:
    blocks = []
    lines = md_text.splitlines()

    current_block_type = None
    current_block_content = []
    current_level = None

    def flush():
        nonlocal current_block_type, current_block_content, current_level
        if not current_block_content:
            return
        content = "\n".join(current_block_content).strip()
        if content:
            block = {"type": current_block_type, "content": content}
            if current_level is not None:
                block["level"] = current_level
            blocks.append(block)
        current_block_content = []
        current_block_type = None
        current_level = None

    i = 0
    while i < len(lines):
        line = lines[i]
        trimmed = line.strip()

        if trimmed.startswith("#"):
            parts = trimmed.split(" ", 1)
            header_symbols = parts[0]
            if all(char == "#" for char in header_symbols) and len(parts) > 1:
                flush()
                current_block_type = "heading"
                current_level = len(header_symbols)
                current_block_content = [parts[1].strip()]
                flush()
                i += 1
                continue

        if trimmed.startswith("|"):
            if current_block_type != "table":
                flush()
                current_block_type = "table"
            current_block_content.append(line)
            i += 1
            continue

        if not trimmed:
            flush()
        else:
            if current_block_type not in ["text", None]:
                flush()
            current_block_type = "text"
            current_block_content.append(line)
        i += 1

    flush()
    return blocks


def _extract_content_topic(text: str) -> Optional[str]:
    """Extract the first meaningful heading or first non-trivial line as the page topic."""
    lines = text.splitlines()
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if re.match(r"^#*\s*Page\s+\d+\s*$", stripped, re.IGNORECASE):
            continue
        if len(stripped) < 3:
            continue
        cleaned = re.sub(r"^[#•–▪\*\-\s]+", "", stripped).strip()
        if 5 <= len(cleaned) <= 120:
            return cleaned
    return None


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------
def main():
    # Render provides PORT, fallback to MARKITDOWN_SERVICE_PORT or 5100
    port = int(os.environ.get("PORT", os.environ.get("MARKITDOWN_SERVICE_PORT", "5100")))
    # Bind to 0.0.0.0 for production (Render requires this), 127.0.0.1 for local dev
    host = os.environ.get("HOST", "0.0.0.0")
    print(f"Starting MarkItDown service on {host}:{port}")
    uvicorn.run(app, host=host, port=port, log_level="info")


if __name__ == "__main__":
    main()
